---

- hosts: all
  become: true
  tasks:
  
  - name: install udpates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install udpates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
    
- hosts: web_servers
  become: true
  tasks:
 
  - name: install apache and php (Ubuntu)
    apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: install apache and php (CentOS)
    dnf:
       name:
         - httpd
         - php
       state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb-server (Ubuntu)
    apt:
       name: mariadb-server
       state: latest
    when: ansible_distribution == "Ubuntu"
