---

- hosts: all
  become: true
  tasks:

  - name: udpate repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: udpate repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: install apache2 package
    dnf:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: add php support for apache
    dnf:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
