---

- hosts: all
  become: true
  tasks:

  - name: udpate repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]
    
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Ubuntu"]

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu"]

  - name: udpate repository index
    tdnf:
      update_cache: yes
    when: ansible_distribution in ["VMware Photon OS"]

  - name: install apache2 package
    tdnf:
      name: apache2
      state: latest
    when: ansible_distribution in ["VMware Photon OS"]

  - name: add php support for apache
    tdnf:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["VMware Photon OS"]
