---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install udpates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
 
  - name: install udpates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php (CentOS)
    tags: apache,httpd,centos
    dnf:
       name:
         - httpd
         - php
       state: latest
    when: ansible_distribution == "CentOS"

  - name: install apache and php (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
    when: ansible_distribution == "Ubuntu"
  
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
       name: mariadb
       state: latest
    when: ansible_distribution == "CentOS"
    
  - name: install mariadb-server (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
       name: mariadb-server
       state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    apt:
       name: samba
       state: latest
